# Generated by Django 2.2.7 on 2019-12-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadopedido',
            old_name='nombre',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='nombre',
            new_name='ingrediente',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='nombre',
            new_name='rol',
        ),
        migrations.RenameField(
            model_name='tipoingrediente',
            old_name='nombre',
            new_name='tipo',
        ),
    ]
