# Generated by Django 2.2.7 on 2019-12-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pictures/%y'),
        ),
    ]
