# Generated by Django 2.2.7 on 2019-12-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesa', '0005_auto_20191207_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadopedido',
            old_name='Estado',
            new_name='estado',
        ),
    ]
