# Generated by Django 2.2.7 on 2019-12-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesa', '0006_auto_20191207_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='atendidopor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
